### ISSUE TITLE
Post this Formula to homebrew-core

### ISSUE THREAD

**Issue by pgreze** [shyiko/homebrew-ktlint#1]
As you discovered in [my issue](https://github.com/Homebrew/homebrew-core/issues/17895), I was trying to package ktlint for Homebrew but after discovering this repo, I was wondering why you didn't just PR this formula to homebrew-core project? (maybe version <= 1.0)

If you're ok for a public release, I can do it for you with this repo's formula.

BTW, thanks for this useful project :)

**Comment by shyiko** [comment]
Hi @pgreze.

The only reason I haven't submitted the PR was "not enough hours in the day" :sob:. I expect `homebrew-core` to have some review process / list of requirements in place and so I took the path that was easier and faster at the time (plus I avoid the delay caused by all this PR business -  `shyiko/ktlint/ktlint` is immediately available upon release). 

That being said, public release would be great and if you are wiling to help out I would definitely appreciate it. The only requirement is that **it has to be automated** (similar to https://github.com/shyiko/ktlint/blob/master/.deploy-to-homebrew, but with a twist - it has to submit the PR (e.g. https://github.com/shyiko/jabba-autodiscovery/blob/master/sync.sh#L33)).

**Comment by shashachu** [comment]
`ktlint` is now part of homebrew-core: https://github.com/Homebrew/homebrew-core/pull/39179
